test:
	cabal v2-test

bin:
	cabal v2-build

clean:
	cabal v2-clean

upstream:
	git remote add upstream https://github.com/ucsd-cse130-mhb/02-lambda.git

update:
	git pull upstream main

turnin:
	git commit -a -m "turnin"
	git push origin main
